# Generated by Django 4.0 on 2022-06-18 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notif', '0001_initial'),
        ('profils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliernotif',
            name='trader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profils.usersprofiles'),
        ),
    ]
