# Generated by Django 4.0 on 2022-06-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notif', '0003_usernotif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliernotif',
            name='body',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='suppliernotif',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usernotif',
            name='body',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usernotif',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
