# Generated by Django 4.0 on 2022-07-06 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notif', '0005_farmtradenotif'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suppliernotif',
            options={'ordering': ['-create_date']},
        ),
        migrations.AlterModelOptions(
            name='usernotif',
            options={'ordering': ['-create_date']},
        ),
    ]
