# Generated by Django 4.0 on 2022-06-18 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountmgt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesaccount',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 6, 26), null=True),
        ),
    ]
