# Generated by Django 4.0 on 2022-06-24 02:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountmgt', '0005_alter_expensesaccount_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesaccount',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 7, 1), null=True),
        ),
    ]
