# Generated by Django 4.0 on 2022-07-11 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0031_alter_orderproduct_due_date'),
        ('profils', '0011_usersprofiles_approve'),
        ('accountmgt', '0008_cashoutaccount_refundaccount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_id', models.PositiveIntegerField(blank=True, null=True)),
                ('transaction_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('symbl', models.CharField(blank=True, max_length=5, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('key', models.CharField(blank=True, max_length=30, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('order', models.ManyToManyField(blank=True, null=True, to='cart.Orders')),
                ('order_product', models.ManyToManyField(blank=True, null=True, to='cart.OrderProduct')),
                ('user_trans', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profils.usersprofiles')),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
    ]
