# Generated by Django 4.0 on 2022-07-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0031_alter_orderproduct_due_date'),
        ('accountmgt', '0009_paymentaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaccount',
            name='order',
            field=models.ManyToManyField(blank=True, to='cart.Orders'),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='order_product',
            field=models.ManyToManyField(blank=True, to='cart.OrderProduct'),
        ),
    ]
