# Generated by Django 4.0 on 2022-07-12 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountmgt', '0010_alter_paymentaccount_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashoutaccount',
            options={'ordering': ['-due_date']},
        ),
    ]
