# Generated by Django 4.0 on 2022-06-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetrade', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='box_approve',
        ),
        migrations.RemoveField(
            model_name='products',
            name='is_box',
        ),
        migrations.AddField(
            model_name='categoryproducts',
            name='name_ar',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='categoryproducts',
            name='name_en',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
