# Generated by Django 4.0 on 2022-06-21 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegetrade', '0005_remove_products_box_name_remove_products_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='our_profit',
        ),
        migrations.RemoveField(
            model_name='products',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='supplier_rev',
        ),
    ]
