# Generated by Django 4.0 on 2022-06-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrymgt', '0007_cityzone_country_cityzone_customer_percent_and_more'),
        ('vegetrade', '0006_remove_products_our_profit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsbox',
            name='city',
        ),
        migrations.RemoveField(
            model_name='productsbox',
            name='country',
        ),
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.CharField(blank=True, choices=[('NEW', 'NEW'), ('UPDATE', 'UPDATE')], default='NEW', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='productsbox',
            name='zone',
            field=models.ManyToManyField(blank=True, to='countrymgt.CityZone'),
        ),
        migrations.AlterField(
            model_name='products',
            name='scale',
            field=models.CharField(blank=True, choices=[('KG', 'KG'), ('BUNCH', 'BUNCH'), ('PIECE', 'PIECE')], max_length=5, null=True),
        ),
    ]
