# Generated by Django 4.0 on 2022-06-21 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegetrade', '0008_remove_productsbox_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsbox',
            name='box_approve',
        ),
    ]
