# Generated by Django 4.0 on 2022-06-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetrade', '0012_productsbulk_alter_products_inv_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='inventory',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productsbox',
            name='inventory',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productsbulk',
            name='inventory',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
