# Generated by Django 4.0 on 2022-06-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetrade', '0018_productsmixed_alter_products_inv_due_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsmixed',
            old_name='discription',
            new_name='description',
        ),
        migrations.AddField(
            model_name='productsmixed',
            name='mix_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
