# Generated by Django 4.0 on 2022-06-29 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetrade', '0020_alter_productsmixed_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='inv_due_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 7, 2), null=True),
        ),
        migrations.AlterField(
            model_name='productsbox',
            name='inv_due_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 7, 2), null=True),
        ),
        migrations.AlterField(
            model_name='productsbulk',
            name='inv_due_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 7, 2), null=True),
        ),
        migrations.AlterField(
            model_name='productsmixed',
            name='inv_due_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 7, 2), null=True),
        ),
        migrations.AlterField(
            model_name='sellingboxproducts',
            name='inv_due_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 7, 2), null=True),
        ),
    ]
