# Generated by Django 4.0 on 2022-06-30 15:48

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetrade', '0022_categoryproducts_country_alter_products_inv_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellingbulkproducts',
            name='inv_due_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 7, 3), null=True),
        ),
        migrations.AddField(
            model_name='sellingbulkproducts',
            name='inventory',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='sellingbulkproducts',
            name='symbl',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='sellingmixedproducts',
            name='inv_due_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 7, 3), null=True),
        ),
        migrations.AddField(
            model_name='sellingmixedproducts',
            name='inventory',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='sellingmixedproducts',
            name='symbl',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='sellingproducts',
            name='inv_due_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 7, 3), null=True),
        ),
        migrations.AddField(
            model_name='sellingproducts',
            name='inventory',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='sellingproducts',
            name='symbl',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='scale',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='productsbulk',
            name='scale',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='productsmixed',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='sellingboxproducts',
            name='inventory',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
