# Generated by Django 4.0 on 2022-06-30 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegetrade', '0023_sellingbulkproducts_inv_due_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductMixedZone',
        ),
    ]
