# Generated by Django 4.0 on 2022-06-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetrade', '0024_delete_productmixedzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproducts',
            name='name_sc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
