# Generated by Django 4.0 on 2022-06-30 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegetrade', '0026_categoryproducts_box_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryproducts',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='categoryproducts',
            name='name_en',
        ),
    ]
