# Generated by Django 4.0 on 2022-06-30 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetrade', '0027_remove_categoryproducts_name_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='inv_due_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 7, 4), null=True),
        ),
        migrations.AlterField(
            model_name='productsbox',
            name='inv_due_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 7, 4), null=True),
        ),
        migrations.AlterField(
            model_name='productsbulk',
            name='inv_due_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 7, 4), null=True),
        ),
        migrations.AlterField(
            model_name='productsmixed',
            name='inv_due_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 7, 4), null=True),
        ),
        migrations.AlterField(
            model_name='sellingboxproducts',
            name='inv_due_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 7, 4), null=True),
        ),
        migrations.AlterField(
            model_name='sellingbulkproducts',
            name='inv_due_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 7, 4), null=True),
        ),
        migrations.AlterField(
            model_name='sellingmixedproducts',
            name='inv_due_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 7, 4), null=True),
        ),
        migrations.AlterField(
            model_name='sellingproducts',
            name='inv_due_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 7, 4), null=True),
        ),
    ]
