# Generated by Django 4.0 on 2022-07-09 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vegetrade', '0036_alter_products_inv_due_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryTransLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_name', models.CharField(blank=True, max_length=50, null=True)),
                ('box_name_sc', models.CharField(blank=True, max_length=50, null=True)),
                ('scale', models.CharField(blank=True, max_length=50, null=True)),
                ('scale_sc', models.CharField(blank=True, max_length=50, null=True)),
                ('retail', models.CharField(blank=True, max_length=50, null=True)),
                ('retail_sc', models.CharField(blank=True, max_length=50, null=True)),
                ('st_accept', models.CharField(blank=True, max_length=50, null=True)),
                ('st_accept_sc', models.CharField(blank=True, max_length=50, null=True)),
                ('st_confirmed', models.CharField(blank=True, max_length=50, null=True)),
                ('st_confirmed_sc', models.CharField(blank=True, max_length=50, null=True)),
                ('st_delivery', models.CharField(blank=True, max_length=50, null=True)),
                ('st_delivery_sc', models.CharField(blank=True, max_length=50, null=True)),
                ('st_delivered', models.CharField(blank=True, max_length=50, null=True)),
                ('st_delivered_sc', models.CharField(blank=True, max_length=50, null=True)),
                ('st_reschedule', models.CharField(blank=True, max_length=50, null=True)),
                ('st_reschedule_sc', models.CharField(blank=True, max_length=50, null=True)),
                ('st_refused', models.CharField(blank=True, max_length=50, null=True)),
                ('st_refused_sc', models.CharField(blank=True, max_length=50, null=True)),
                ('st_cancelled', models.CharField(blank=True, max_length=50, null=True)),
                ('st_cancelled_sc', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='categoryproducts',
            name='lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vegetrade.countrytranslang'),
        ),
    ]
