# Generated by Django 4.0 on 2022-07-09 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegetrade', '0037_countrytranslang_categoryproducts_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryproducts',
            name='box_name',
        ),
        migrations.RemoveField(
            model_name='categoryproducts',
            name='box_name_sc',
        ),
        migrations.RemoveField(
            model_name='categoryproducts',
            name='retail',
        ),
        migrations.RemoveField(
            model_name='categoryproducts',
            name='retail_sc',
        ),
        migrations.RemoveField(
            model_name='categoryproducts',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='categoryproducts',
            name='scale_sc',
        ),
        migrations.RemoveField(
            model_name='categoryproducts',
            name='st_accept',
        ),
        migrations.RemoveField(
            model_name='categoryproducts',
            name='st_accept_sc',
        ),
        migrations.RemoveField(
            model_name='categoryproducts',
            name='st_cancelled',
        ),
        migrations.RemoveField(
            model_name='categoryproducts',
            name='st_cancelled_sc',
        ),
        migrations.RemoveField(
            model_name='categoryproducts',
            name='st_confirmed',
        ),
        migrations.RemoveField(
            model_name='categoryproducts',
            name='st_confirmed_sc',
        ),
        migrations.RemoveField(
            model_name='categoryproducts',
            name='st_delivered',
        ),
        migrations.RemoveField(
            model_name='categoryproducts',
            name='st_delivered_sc',
        ),
        migrations.RemoveField(
            model_name='categoryproducts',
            name='st_delivery',
        ),
        migrations.RemoveField(
            model_name='categoryproducts',
            name='st_delivery_sc',
        ),
        migrations.RemoveField(
            model_name='categoryproducts',
            name='st_refused',
        ),
        migrations.RemoveField(
            model_name='categoryproducts',
            name='st_refused_sc',
        ),
        migrations.RemoveField(
            model_name='categoryproducts',
            name='st_reschedule',
        ),
        migrations.RemoveField(
            model_name='categoryproducts',
            name='st_reschedule_sc',
        ),
    ]
