# Generated by Django 4.0 on 2022-06-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('subject_ar', models.CharField(blank=True, max_length=100, null=True)),
                ('subject_en', models.CharField(blank=True, max_length=100, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('answer_ar', models.TextField(blank=True, null=True)),
                ('answer_en', models.TextField(blank=True, null=True)),
                ('faq_section', models.CharField(blank=True, choices=[('GENERAL', 'GENERAL'), ('DELIVERY', 'DELIVERY'), ('RETURN', 'RETURN'), ('GROWING', 'GROWING'), ('PRIVACY', 'PRIVACY'), ('TRADER', 'TRADER'), ('TRPOLICY', 'TRPOLICY')], max_length=100, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
    ]
