# Generated by Django 4.0 on 2022-07-02 12:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import support.models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0023_alter_orderproduct_due_date'),
        ('profils', '0008_supporterprofiles'),
        ('support', '0003_remove_faqsupport_answer_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('supporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profils.supporterprofiles')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profils.usersprofiles')),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='SupportContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_link', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='faqsupport',
            name='faq_section',
            field=models.CharField(blank=True, choices=[('GENERAL', 'GENERAL'), ('DELIVERY', 'DELIVERY'), ('RETURN', 'RETURN'), ('GROWER', 'GROWER'), ('PRIVACY', 'PRIVACY'), ('TRADER', 'TRADER'), ('TRPOLICY', 'TRPOLICY')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='TicketSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('dep', models.CharField(blank=True, choices=[('ACCOUNT', 'ACCOUNT'), ('QUALITY', 'QUALITY'), ('TECHNICAL', 'TECHNICAL'), ('GENERAL', 'GENERAL'), ('SALES', 'SALES')], max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.orders')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profils.usersprofiles')),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='TicketFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to=support.models.support_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg', 'pdf'])])),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.ticketsupport')),
            ],
        ),
        migrations.CreateModel(
            name='TicketAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
                ('dep', models.CharField(blank=True, choices=[('ACCOUNT', 'ACCOUNT'), ('QUALITY', 'QUALITY'), ('TECHNICAL', 'TECHNICAL'), ('GENERAL', 'GENERAL'), ('SALES', 'SALES')], max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('reply', models.BooleanField(default=False, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='support.ticketsupport')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profils.usersprofiles')),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='FarmSupportAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
                ('reply', models.BooleanField(default=False, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='support.farmsupport')),
                ('supporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profils.supporterprofiles')),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='FarmMacth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('supporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profils.supporterprofiles')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profils.usersprofiles')),
            ],
        ),
        migrations.CreateModel(
            name='FarmFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to=support.models.farm_support_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg', 'pdf'])])),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.farmsupport')),
                ('case_ans', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.farmsupportanswers')),
            ],
        ),
    ]
