# Generated by Django 4.0 on 2022-07-03 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profils', '0009_supporterprofiles_experience_supporterprofiles_fees'),
        ('support', '0005_remove_farmsupport_country_farmmacth_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmsupportanswers',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profils.usersprofiles'),
        ),
    ]
