# Generated by Django 4.0 on 2022-07-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_farmsupportanswers_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsupport',
            name='status',
            field=models.CharField(blank=True, choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED'), ('PROCESSING', 'PROCESSING')], max_length=100, null=True),
        ),
    ]
