# Generated by Django 4.0 on 2022-07-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_ticketsupport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketfiles',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
