# Generated by Django 4.0 on 2022-07-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_ticketfiles_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsupport',
            name='status',
            field=models.CharField(blank=True, choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED'), ('PROCESSING', 'PROCESSING')], default='OPEN', max_length=100, null=True),
        ),
    ]
