# Generated by Django 4.0 on 2022-07-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0009_alter_ticketsupport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmsupport',
            name='status',
            field=models.CharField(blank=True, choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED'), ('PROCESSING', 'PROCESSING')], default='OPEN', max_length=100, null=True),
        ),
    ]
