# Generated by Django 4.0 on 2022-06-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrymgt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrymanager',
            name='second_lang',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
