# Generated by Django 4.0 on 2022-06-20 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countrymgt', '0003_remove_countrymanager_shipping_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(blank=True, max_length=50, null=True)),
                ('lat_greater', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=50, null=True)),
                ('lat_lower', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=50, null=True)),
                ('long_greater', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=50, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='countrymgt.countrymanager')),
            ],
        ),
    ]
