# Generated by Django 4.0 on 2022-06-22 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrymgt', '0007_cityzone_country_cityzone_customer_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrymanager',
            name='tax',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
