# Generated by Django 4.0 on 2022-06-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrymgt', '0008_alter_countrymanager_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=50, null=True)),
                ('long', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=50, null=True)),
            ],
        ),
    ]
