# Generated by Django 4.0 on 2022-06-22 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countrymgt', '0009_newzone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountryUserConst',
        ),
    ]
