# Generated by Django 4.0 on 2022-06-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrymgt', '0010_delete_countryuserconst'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityzone',
            name='duedate',
            field=models.PositiveIntegerField(blank=True, default=7, null=True),
        ),
    ]
