# Generated by Django 4.0 on 2022-06-26 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countrymgt', '0011_cityzone_duedate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountryAppConst',
        ),
    ]
