# Generated by Django 4.0 on 2022-06-27 17:20

import countrymgt.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrymgt', '0012_delete_countryappconst'),
    ]

    operations = [
        migrations.AddField(
            model_name='citymanagement',
            name='file_upload',
            field=models.FileField(blank=True, default='farm_default.jpg', null=True, upload_to=countrymgt.models.city_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])]),
        ),
        migrations.AddField(
            model_name='countrymanager',
            name='file_upload',
            field=models.FileField(blank=True, default='farm_default.jpg', null=True, upload_to=countrymgt.models.country_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])]),
        ),
        migrations.AddField(
            model_name='newzone',
            name='is_trader',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
