# Generated by Django 4.0 on 2022-06-27 17:30

import countrymgt.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrymgt', '0013_citymanagement_file_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrymanager',
            name='file_upload',
            field=models.FileField(blank=True, default='farm_default.jpg', null=True, upload_to=countrymgt.models.country_path),
        ),
    ]
