# Generated by Django 4.0 on 2022-07-02 12:56

import admanager.models
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profils', '0007_profilesmsg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertesing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, default='No Address', null=True)),
                ('postal_code', models.CharField(blank=True, default='No Postal Code', max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.CharField(blank=True, default='No Area', max_length=50, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=50, null=True)),
                ('long', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=50, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to=admanager.models.ads_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])])),
                ('msg', models.TextField(null=True)),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
                ('due', models.DateField(blank=True, default=datetime.date(2022, 8, 1), null=True)),
                ('terms', models.BooleanField(blank=True, default=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admanager.advertesing')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profils.usersprofiles')),
            ],
        ),
    ]
