# Generated by Django 4.0 on 2022-07-03 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admanager', '0002_advertesing_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertesing',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='advertesing',
            name='due',
            field=models.DateField(blank=True, default=datetime.date(2022, 8, 2), null=True),
        ),
    ]
