# Generated by Django 4.0 on 2022-07-08 01:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admanager', '0007_alter_advertesing_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertesing',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='advertesing',
            name='due',
            field=models.DateField(blank=True, default=datetime.date(2022, 8, 7), null=True),
        ),
    ]
