TRACKFIELD = [
    ('ORDER RECEIVED', 'ORDER RECEIVED'),
    ('PROCESSING', 'PROCESSING'),
    ('DELIVERY OUT', 'DELIVERY OUT'),
    ('DELIVERED', 'DELIVERED'),
    ('UNABLE TO DELIVER ONE ITEM', 'UNABLE TO DELIVER ONE ITEM'),
    ('CANCELLED', 'CANCELLED'),
    ('ITEMS DELIVERY OUT', 'ITEMS DELIVERY OUT'),
]
