# Generated by Django 4.0 on 2022-06-22 00:22

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countrymgt', '0008_alter_countrymanager_tax'),
        ('vegefarm', '0003_alter_farmproducts_inv_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmproducts',
            name='box_name',
        ),
        migrations.RemoveField(
            model_name='farmproducts',
            name='city',
        ),
        migrations.RemoveField(
            model_name='farmproducts',
            name='country',
        ),
        migrations.RemoveField(
            model_name='farmproducts',
            name='our_profit',
        ),
        migrations.RemoveField(
            model_name='farmproducts',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='farmproducts',
            name='supplier_rev',
        ),
        migrations.RemoveField(
            model_name='farmsellingproducts',
            name='box_name',
        ),
        migrations.RemoveField(
            model_name='farmsellingproducts',
            name='city',
        ),
        migrations.RemoveField(
            model_name='farmsellingproducts',
            name='country',
        ),
        migrations.RemoveField(
            model_name='farmsellingproducts',
            name='inv_due_date',
        ),
        migrations.RemoveField(
            model_name='farmsellingproducts',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='farmsellingproducts',
            name='is_box',
        ),
        migrations.RemoveField(
            model_name='farmsellingproducts',
            name='price',
        ),
        migrations.RemoveField(
            model_name='farmsellingproducts',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='farmsellingproducts',
            name='symbl',
        ),
        migrations.AddField(
            model_name='farmproducts',
            name='hydro',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='farmproducts',
            name='status',
            field=models.CharField(blank=True, choices=[('NEW', 'NEW'), ('UPDATE', 'UPDATE')], default='NEW', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='farmsellingproducts',
            name='zone',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='countrymgt.cityzone'),
        ),
        migrations.AlterField(
            model_name='farmproducts',
            name='scale',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='farmsellingproducts',
            name='hydro',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.CreateModel(
            name='FarmProductZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('supplier_rev', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('our_profit', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vegefarm.farmproducts')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='countrymgt.cityzone')),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
    ]
