# Generated by Django 4.0 on 2022-06-22 22:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegefarm', '0004_remove_farmproducts_box_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmproducts',
            name='inv_due_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 6, 26), null=True),
        ),
    ]
