# Generated by Django 4.0 on 2022-06-30 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegefarm', '0013_alter_farmproducts_inv_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmproductsbulk',
            name='hydro',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='farmsellingproducts',
            name='inv_due_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 7, 3), null=True),
        ),
        migrations.AddField(
            model_name='farmsellingproducts',
            name='inventory',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='farmsellingproducts',
            name='symbl',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='sellingfarmbulkproducts',
            name='hydro',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='sellingfarmbulkproducts',
            name='inv_due_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 7, 3), null=True),
        ),
        migrations.AddField(
            model_name='sellingfarmbulkproducts',
            name='inventory',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='sellingfarmbulkproducts',
            name='symbl',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='farmproductsbulk',
            name='scale',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
