# Generated by Django 4.0 on 2022-07-02 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegefarm', '0017_rename_inv_due_date_farmgrow_due_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmgrow',
            old_name='due_date',
            new_name='inv_due_date',
        ),
        migrations.RemoveField(
            model_name='farmgrow',
            name='system',
        ),
    ]
