# Generated by Django 4.0 on 2022-07-03 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegefarm', '0018_rename_due_date_farmgrow_inv_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmgrow',
            name='inv_due_date',
        ),
        migrations.AddField(
            model_name='farmgrow',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 8, 2), null=True),
        ),
        migrations.AddField(
            model_name='farmgrow',
            name='system',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='farmproducts',
            name='inv_due_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 8, 2), null=True),
        ),
        migrations.AlterField(
            model_name='farmproductsbulk',
            name='inv_due_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 8, 2), null=True),
        ),
        migrations.AlterField(
            model_name='farmsellingproducts',
            name='inv_due_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 8, 2), null=True),
        ),
        migrations.AlterField(
            model_name='sellingfarmbulkproducts',
            name='inv_due_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 8, 2), null=True),
        ),
    ]
