# Generated by Django 4.0 on 2022-06-18 17:24

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countrymgt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbl', models.CharField(blank=True, max_length=5, null=True)),
                ('buy_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('supplier_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('transaction_id', models.IntegerField(blank=True, null=True)),
                ('scale', models.CharField(blank=True, max_length=5, null=True)),
                ('box_name', models.CharField(blank=True, default='Single', max_length=25, null=True)),
                ('is_box', models.BooleanField(blank=True, default=False, null=True)),
                ('hydro', models.BooleanField(blank=True, default=False, null=True)),
                ('due_date', models.DateField(blank=True, default=datetime.date(2022, 6, 19), null=True)),
                ('status', models.CharField(blank=True, choices=[('CREATED', 'CREATED'), ('PAID', 'PAID'), ('ACCEPT', 'ACCEPT'), ('REJECT', 'REJECT'), ('COLLECTION POINT', 'COLLECTION POINT'), ('RECEIVED', 'RECEIVED'), ('COLLECTION POINT', 'COLLECTION POINT'), ('READY TO DELIVERY', 'READY TO DELIVERY'), ('SHIPPED', 'SHIPPED'), ('CANCELLED', 'CANCELLED'), ('REFUND', 'REFUND'), ('REJECT', 'REJECT'), ('RETURN', 'RETURN'), ('ASSIGNED', 'ASSIGNED'), ('OUT FOR DELIVERY', 'OUT FOR DELIVERY'), ('DELIVERED', 'DELIVERED'), ('UNABLE TO DELIVERY', 'UNABLE TO DELIVERY'), ('PICK UP', 'PICK UP'), ('CONFIRMED', 'CONFIRMED'), ('COLLECTED', 'COLLECTED'), ('RECEIVED', 'RECEIVED'), ('TRANSFERED', 'TRANSFERED'), ('FIXED', 'FIXED'), ('RATE', 'RATE'), ('CPC', 'CPC'), ('DATE', 'DATE'), ('SPONSOR', 'SPONSOR'), ('ADPAID', 'ADPAID'), ('PENDING', 'PENDING'), ('UNEARNED REVENUE', 'UNEARNED REVENUE'), ('OFFER', 'OFFER'), ('EXECUTED', 'EXECUTED'), ('MARKET', 'MARKET'), ('OFFER REMOVED', 'OFFER REMOVED'), ('LOST SELL', 'LOST SELL')], default='CREATED', max_length=20, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_total', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('shipping', models.IntegerField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('symbl', models.CharField(blank=True, max_length=5, null=True)),
                ('items', models.IntegerField(blank=True, null=True)),
                ('coupon', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('transaction_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('note', models.TextField(blank=True, default='No Note', null=True)),
                ('status', models.CharField(blank=True, choices=[('CREATED', 'CREATED'), ('PAID', 'PAID'), ('ACCEPT', 'ACCEPT'), ('REJECT', 'REJECT'), ('COLLECTION POINT', 'COLLECTION POINT'), ('RECEIVED', 'RECEIVED'), ('COLLECTION POINT', 'COLLECTION POINT'), ('READY TO DELIVERY', 'READY TO DELIVERY'), ('SHIPPED', 'SHIPPED'), ('CANCELLED', 'CANCELLED'), ('REFUND', 'REFUND'), ('REJECT', 'REJECT'), ('RETURN', 'RETURN'), ('ASSIGNED', 'ASSIGNED'), ('OUT FOR DELIVERY', 'OUT FOR DELIVERY'), ('DELIVERED', 'DELIVERED'), ('UNABLE TO DELIVERY', 'UNABLE TO DELIVERY'), ('PICK UP', 'PICK UP'), ('CONFIRMED', 'CONFIRMED'), ('COLLECTED', 'COLLECTED'), ('RECEIVED', 'RECEIVED'), ('TRANSFERED', 'TRANSFERED'), ('FIXED', 'FIXED'), ('RATE', 'RATE'), ('CPC', 'CPC'), ('DATE', 'DATE'), ('SPONSOR', 'SPONSOR'), ('ADPAID', 'ADPAID'), ('PENDING', 'PENDING'), ('UNEARNED REVENUE', 'UNEARNED REVENUE'), ('OFFER', 'OFFER'), ('EXECUTED', 'EXECUTED'), ('MARKET', 'MARKET'), ('OFFER REMOVED', 'OFFER REMOVED'), ('LOST SELL', 'LOST SELL')], default='CREATED', max_length=20, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='countrymgt.citymanagement')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='countrymgt.countrymanager')),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
    ]
