# Generated by Django 4.0 on 2022-06-18 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('vegetrade', '0001_initial'),
        ('countrymgt', '0001_initial'),
        ('profils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profils.usersprofiles'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='countrymgt.citymanagement'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='countrymgt.countrymanager'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.orders'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vegetrade.sellingproducts'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vegetrade.categoryproducts'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vegetrade.products'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='trader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profils.usersprofiles'),
        ),
    ]
