# Generated by Django 4.0 on 2022-06-18 22:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vegefarm', '0001_initial'),
        ('cart', '0004_rename_price_orderproduct_market_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='farm_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vegefarm.farmsellingproducts'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='farm_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vegefarm.farmproducts'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 6, 20), null=True),
        ),
    ]
