# Generated by Django 4.0 on 2022-06-20 22:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_orderproduct_farm_item_orderproduct_farm_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 6, 22), null=True),
        ),
    ]
