# Generated by Django 4.0 on 2022-06-22 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countrymgt', '0008_alter_countrymanager_tax'),
        ('vegetrade', '0011_alter_sellingboxproducts_zone_and_more'),
        ('cart', '0007_alter_orderproduct_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='city',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='country',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='market_item',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='city',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='country',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='box_market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vegetrade.productsbox'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='countrymgt.cityzone'),
        ),
        migrations.AddField(
            model_name='orders',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='countrymgt.cityzone'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='box_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vegetrade.sellingboxproducts'),
        ),
    ]
