# Generated by Django 4.0 on 2022-06-22 22:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_remove_orderproduct_city_remove_orderproduct_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 6, 24), null=True),
        ),
    ]
