# Generated by Django 4.0 on 2022-06-23 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vegetrade', '0013_alter_products_inventory_alter_productsbox_inventory_and_more'),
        ('cart', '0011_alter_orderproduct_bulk_market_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='box_market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vegetrade.sellingboxproducts'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='box_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vegetrade.productsbox'),
        ),
    ]
