# Generated by Django 4.0 on 2022-06-23 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vegefarm', '0006_farmproductsbulk_alter_farmproducts_inventory_and_more'),
        ('cart', '0012_alter_orderproduct_box_market_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='bulk_farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vegefarm.sellingfarmbulkproducts'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='bulk_farm_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vegefarm.farmproductsbulk'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='is_farm_bulk',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
