# Generated by Django 4.0 on 2022-06-29 17:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vegetrade', '0021_alter_products_inv_due_date_and_more'),
        ('cart', '0019_alter_orderproduct_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='is_mix',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='mix_market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vegetrade.sellingmixedproducts'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='mix_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vegetrade.productsmixed'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 6, 30), null=True),
        ),
    ]
