# Generated by Django 4.0 on 2022-06-30 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0021_orders_payment_result_orders_tran_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 7, 2), null=True),
        ),
    ]
