# Generated by Django 4.0 on 2022-06-18 17:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import profils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countrymgt', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, default='No Address', null=True)),
                ('postal_code', models.CharField(blank=True, default='No Postal Code', max_length=50, null=True)),
                ('symbl', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.CharField(blank=True, default='No Area', max_length=50, null=True)),
                ('terms', models.BooleanField(blank=True, default=True, null=True)),
                ('trader_name', models.CharField(blank=True, max_length=150, null=True)),
                ('is_trader', models.BooleanField(blank=True, default=False, null=True)),
                ('farm_name', models.CharField(blank=True, max_length=150, null=True)),
                ('is_farm', models.BooleanField(blank=True, default=False, null=True)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='countrymgt.citymanagement')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='countrymgt.countrymanager')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, default='farm_default.jpg', null=True, upload_to=profils.models.trader_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])])),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profils.usersprofiles')),
            ],
        ),
    ]
