# Generated by Django 4.0 on 2022-06-18 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraderTransData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.TextField(blank=True, default='None', null=True)),
                ('new', models.TextField(blank=True, null=True)),
                ('change', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('benfec', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profils.usersprofiles')),
            ],
        ),
    ]
