# Generated by Django 4.0 on 2022-06-22 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countrymgt', '0008_alter_countrymanager_tax'),
        ('profils', '0003_profileszone'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprofiles',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='countrymgt.cityzone'),
        ),
        migrations.AlterField(
            model_name='usersprofiles',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usersprofiles',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
