# Generated by Django 4.0 on 2022-06-26 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profils', '0005_usersprofiles_lat_usersprofiles_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradertransdata',
            name='current',
            field=models.TextField(blank=True, default='No Account Data', null=True),
        ),
    ]
