# Generated by Django 4.0 on 2022-07-02 12:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import profils.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('profils', '0007_profilesmsg'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupporterProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, default='No Address', null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=profils.models.supporter_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg', 'pdf'])])),
                ('terms', models.BooleanField(blank=True, default=True, null=True)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
