# Generated by Django 4.0 on 2022-07-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profils', '0010_profilephotos_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprofiles',
            name='approve',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
