# Generated by Django 4.0 on 2022-07-07 15:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0028_alter_orderproduct_due_date'),
        ('tracker', '0014_alter_ordertracking_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborderreview',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.orders'),
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 7, 8), null=True),
        ),
        migrations.AlterField(
            model_name='subordertracking',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 7, 8), null=True),
        ),
    ]
